services:
  - type: web
    name: secure-desk-tracker
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput --clear
    releaseCommand: python manage.py migrate --noinput
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "9a6bd6c7e6333f2451d8e76e825c6adb"
      - key: DATABASE_URL
        value: "postgresql://database_bunb_user:JY5sybHn5waNfNWYcGnoSF4anGTCMRf1@dpg-d8fg88uq1p3s73eog19g-a:5432/database_bunb?sslmode=require"
      - key: ALLOWED_HOSTS
        value: "it-helpdesk-security-incident-tracker-6l52.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://it-helpdesk-security-incident-tracker-6l52.onrender.com"
