services:
  - type: web
    name: secure-desk-tracker
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput --clear
    releaseCommand: python manage.py migrate --noinput
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "it-helpdesk-security-incident-tracker-6l52.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://it-helpdesk-security-incident-tracker-6l52.onrender.com"
