# Generated by Django 6.0.5 on 2026-06-02 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0006_incidentticket_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentticket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filemanager.category'),
        ),
        migrations.AddField(
            model_name='incidentticket',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10),
        ),
    ]
