# Generated by Django 6.0.5 on 2026-06-03 03:16

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0009_incidentattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentattachment',
            name='file',
            field=models.FileField(max_length=255, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='incident_attachments/'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(max_length=255, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='ticket_attachments/'),
        ),
    ]
